"""AI service endpoints (Master Spec section 47).

Every route is a thin adapter over app/engines and app/services. No business
rule lives here, which is why the test suite can verify the whole system
without starting a web server.
"""
from __future__ import annotations

import logging
import time
from typing import Any, Dict, List

from fastapi import APIRouter, Depends, HTTPException

from ..copilot.llm import LLMClient
from ..engines.evidence import SYSTEM_POLICY
from ..engines.extraction import extract_from_rows, extract_from_text
from ..engines.factor_resolver import FactorResolutionError
from ..engines.retrieval import RetrievalContext
from ..schemas.api import (AnalyseRequest, CopilotRequest, CurveRequest,
                           ExtractRowsRequest, ExtractTextRequest, OptimiseRequest,
                           ResolveRequest, SimulateRequest)
from ..services.demo_factory import load as load_demo
from .deps import rate_limit, require_service_token, state, to_domain

log = logging.getLogger("ecoforge.api")
router = APIRouter(dependencies=[Depends(rate_limit), Depends(require_service_token)])


def _analyse(req: AnalyseRequest):
    st = state()
    ctx, records, cons, history, processes = to_domain(req)
    t0 = time.perf_counter()
    result = st.service.analyse(ctx, records, view=req.view, constraints=cons,
                                history=history, process_records=processes)
    log.info("analysed factory=%s records=%d in %.0f ms", ctx.factory_id,
             len(records), (time.perf_counter() - t0) * 1000)
    return st, result


# --------------------------------------------------------------------------
@router.get("/health")
def health() -> Dict[str, Any]:
    return state().health()


@router.get("/factors/sources")
def factor_sources() -> Dict[str, Any]:
    st = state()
    by_source: Dict[str, Dict[str, Any]] = {}
    for f in st.repo.factors():
        e = by_source.setdefault(f.source, {
            "source": f.source, "dataset_name": f.dataset_name,
            "dataset_version": f.dataset_version, "publisher": f.publisher,
            "source_url": f.source_url, "geography": f.geography,
            "count": 0, "categories": set(), "years": set()})
        e["count"] += 1
        e["categories"].add(f.category)
        if f.year:
            e["years"].add(f.year)
    out = []
    for e in by_source.values():
        e["categories"] = sorted(e["categories"])
        e["years"] = sorted(e["years"])
        out.append(e)
    return {"sources": out, "total": len(st.repo.factors())}


@router.post("/factors/resolve")
def resolve_factor(req: ResolveRequest) -> Dict[str, Any]:
    st = state()
    try:
        chosen, candidates, notes = st.service.resolver.resolve_energy(
            req.activity_key, req.unit, req.country_code, req.year, req.grid_region)
    except FactorResolutionError as exc:
        raise HTTPException(400, str(exc)) from exc
    return {
        "chosen": chosen.to_dict() if chosen else None,
        "reconciliation": st.service.resolver.reconcile(candidates),
        "candidates": [c.to_dict() for c in candidates],
        "notes": notes,
        "policy": st.repo.policy(
            chosen.factor.category if chosen else "electricity", req.country_code),
    }


@router.post("/ai/extract")
def extract(req: ExtractTextRequest) -> Dict[str, Any]:
    cands = extract_from_text(req.text)
    return {
        "candidates": [c.to_dict() for c in cands],
        "requires_confirmation": [c.to_dict() for c in cands if c.needs_confirmation],
        "note": ("Numbers are read out of your own text by a deterministic parser. "
                 "Nothing here was generated by a language model, and nothing is "
                 "saved until you confirm it."),
    }


@router.post("/ai/extract/rows")
def extract_rows(req: ExtractRowsRequest) -> Dict[str, Any]:
    cands = extract_from_rows(req.rows)
    return {"candidates": [c.to_dict() for c in cands],
            "unreadable": [c.to_dict() for c in cands
                           if c.record_type == "UNREADABLE"]}


@router.post("/ai/analyse")
def analyse(req: AnalyseRequest) -> Dict[str, Any]:
    _, result = _analyse(req)
    return result.summary()


@router.post("/ai/retrieve")
def retrieve(req: AnalyseRequest) -> Dict[str, Any]:
    st, result = _analyse(req)
    rc = RetrievalContext.build(result.ctx, [r for r in result.footprint.calculations],
                                result.hotspots)
    return {"query": rc.to_query(),
            "results": [r.to_dict() for r in result.retrieved],
            "embedding_model": st.embedder.name,
            "degraded": st.embedder.degraded}


@router.post("/ai/rerank")
def rerank(req: AnalyseRequest) -> Dict[str, Any]:
    _, result = _analyse(req)
    return {"ranked": [{"slug": r.intervention.slug,
                        "semantic": round(r.semantic, 4),
                        "hybrid": round(r.hybrid, 4),
                        "reasons": r.reasons} for r in result.retrieved]}


@router.post("/ai/optimize")
def optimize(req: OptimiseRequest) -> Dict[str, Any]:
    st, result = _analyse(req)
    return st.service.optimise(result, req.budget_inr).to_dict()


@router.post("/ai/optimize/curve")
def optimize_curve(req: CurveRequest) -> Dict[str, Any]:
    st, result = _analyse(req)
    return {"curve": st.service.budget_curve(result, req.budgets)}


@router.post("/ai/simulate")
def simulate(req: SimulateRequest) -> Dict[str, Any]:
    st, result = _analyse(req)
    return st.service.simulate(result, req.selection)


@router.post("/ai/anomaly")
def anomaly(req: AnalyseRequest) -> Dict[str, Any]:
    _, result = _analyse(req)
    return {"results": [a.to_dict() for a in result.anomalies]}


@router.post("/ai/action-plan")
def action_plan(req: OptimiseRequest) -> Dict[str, Any]:
    st, result = _analyse(req)
    plan, portfolio = st.service.action_plan(result, req.budget_inr)
    return {"plan": plan, "portfolio": portfolio.to_dict()}


@router.post("/ai/evidence")
def evidence(req: CopilotRequest) -> Dict[str, Any]:
    st, result = _analyse(req)
    portfolio = (st.service.optimise(result, req.budget_inr)
                 if req.budget_inr else None)
    scenario = st.service.simulate(result, req.selection) if req.selection else None
    return st.service.evidence_pack(result, req.question, portfolio, scenario)


@router.post("/ai/copilot")
async def copilot(req: CopilotRequest) -> Dict[str, Any]:
    st, result = _analyse(req)
    portfolio = (st.service.optimise(result, req.budget_inr)
                 if req.budget_inr else None)
    scenario = st.service.simulate(result, req.selection) if req.selection else None
    pack = st.service.evidence_pack(result, req.question, portfolio, scenario)
    answer, meta = await LLMClient().explain(pack, req.question)
    return {"answer": answer, "meta": meta,
            "evidence_summary": {
                "leaks": [h.to_dict() for h in result.hotspots[:5]],
                "hard_limits": pack["hard_limits"]},
            "policy": SYSTEM_POLICY}


@router.post("/ai/explain")
async def explain(req: CopilotRequest) -> Dict[str, Any]:
    return await copilot(req)


@router.get("/demo/factory")
def demo_factory() -> Dict[str, Any]:
    ctx, records, history, processes = load_demo()
    return {
        "factory": ctx.__dict__,
        "records": [r.__dict__ for r in records],
        "history": [{"period": h.period, "production": h.production,
                     "values": h.values} for h in history],
        "processes": [p.__dict__ for p in processes],
        "note": ("Only operational inputs are stored for the demo factory. Every "
                 "emission, leak, recommendation, cost and scenario value is "
                 "calculated at runtime from the loaded factor table."),
    }
